# Generated by Django 3.0.7 on 2020-06-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='imdb_rating',
            field=models.FloatField(),
        ),
    ]
