# Generated by Django 3.0.7 on 2020-06-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200620_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
