# Generated by Django 3.0.7 on 2020-06-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200621_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5'), ('Six', '6'), ('Seven', '7'), ('Eight', '8'), ('Nine', '9'), ('Ten', '10')], default='Five', max_length=5),
        ),
    ]
