# Generated by Django 3.0.7 on 2020-06-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200623_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='performers',
            field=models.ManyToManyField(to='main_app.Performer'),
        ),
    ]
